# -*- coding: utf-8 -*-
"""Copy of Tiger_AI_System_Complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5Yy_5WJ8ZkvRgd7mJXUidhFMU1sB8fr

# 🐯 Tiger AI Detection & Classification System
### Complete Pipeline — Forest Department Wildlife Monitoring

---

## What This Notebook Does
1. **Model 1 — Tiger Detector (YOLOv8):** Detects and counts ALL tigers in every image
2. **Model 2 — Tiger Classifier (EfficientNetB3):** Classifies each tiger into one of 5 types
3. **Final Pipeline:** Combines both models to generate a complete forest population report

## Your Folder Structure Expected in Google Drive
```
My Drive/
└── Tiger_Project/
    ├── dataset/
    │   ├── tiger/           ← 329 tiger images (all types mixed)
    │   └── no_tiger/        ← 253 non-tiger images
    ├── tiger_types/
    │   ├── orange_tiger/    ← 104 images
    │   ├── white_tiger/     ← 80 images
    │   ├── golden_tiger/    ← 49 images
    │   ├── black_tiger/     ← 56 images
    │   └── snow_white_tiger/← 40 images
    ├── models/              ← trained models saved here
    ├── test_images/         ← new images to test on
    └── roboflow_dataset/    ← extracted Roboflow ZIP goes here
```

## Before Running
1. Go to **Runtime → Change runtime type → T4 GPU → Save**
2. Extract your Roboflow ZIP and upload the folder to `Tiger_Project/roboflow_dataset/`
3. Run cells **one by one** from top to bottom

---

## SECTION 1 — SETUP
### Cell 1.1 — Check GPU and Mount Google Drive
"""

# ============================================================
# CELL 1.1 — CHECK GPU + MOUNT GOOGLE DRIVE
# ============================================================

import subprocess

# Check if GPU is available
gpu_info = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
if gpu_info.returncode == 0:
    print('✅ GPU is available and ready!')
    print(gpu_info.stdout[:300])
else:
    print('❌ NO GPU DETECTED!')
    print('ACTION REQUIRED:')
    print('Go to Runtime → Change runtime type → T4 GPU → Save')
    print('Then restart and run this cell again')
    raise SystemExit('Please enable GPU before continuing')

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
print('\n✅ Google Drive mounted successfully!')

"""### Cell 1.2 — Install All Required Libraries"""

# ============================================================
# CELL 1.2 — INSTALL ALL LIBRARIES
# This takes 2-3 minutes. Wait for it to complete.
# ============================================================

print('Installing libraries... please wait (2-3 minutes)...')

import subprocess
subprocess.run(['pip', 'install', 'ultralytics', '-q'], check=True)
subprocess.run(['pip', 'install', 'opencv-python-headless', '-q'], check=True)
subprocess.run(['pip', 'install', 'seaborn', '-q'], check=True)

# Verify installations
import ultralytics
import cv2
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import os, shutil, yaml, json, warnings
warnings.filterwarnings('ignore')

print('\n✅ All libraries installed successfully!')
print(f'   Ultralytics version : {ultralytics.__version__}')
print(f'   TensorFlow version  : {tf.__version__}')
print(f'   OpenCV version      : {cv2.__version__}')
print(f'   GPU devices         : {tf.config.list_physical_devices("GPU")}')

"""### Cell 1.3 — Configure All Paths (Edit This Cell If Your Folder Names Are Different)"""

# ============================================================
# CELL 1.3 — CONFIGURE PATHS
# If your folder names are different, change them here ONLY
# ============================================================

import os

# ── ROOT PATH (change only if your project folder has a different name)
PROJECT_ROOT = '/content/drive/MyDrive/Tiger_Project'

# ── DATASET PATHS (Model 1 - YOLO)
DATASET_PATH       = f'{PROJECT_ROOT}/dataset'
TIGER_PATH         = f'{DATASET_PATH}/tiger'
NO_TIGER_PATH      = f'{DATASET_PATH}/no_tiger'
ROBOFLOW_PATH      = f'{DATASET_PATH}/roboflow_dataset'
YAML_PATH          = f'{ROBOFLOW_PATH}/data.yaml'

# ── TIGER TYPES PATHS (Model 2 - EfficientNetB3)
TIGER_TYPES_PATH   = f'{PROJECT_ROOT}/tiger_types'

# ── OUTPUT PATHS
MODELS_PATH        = f'{PROJECT_ROOT}/models'
TEST_IMAGES_PATH   = f'{PROJECT_ROOT}/test_images'
YOLO_MODEL_PATH    = f'{MODELS_PATH}/tiger_detector/weights/best.pt'
EFFNET_MODEL_PATH  = f'{MODELS_PATH}/tiger_classifier.keras'
REPORT_PATH        = f'{PROJECT_ROOT}/tiger_population_report.txt'

# ── TIGER TYPE LABELS (must match your folder names exactly)
TIGER_TYPES = ['black_tiger', 'golden_tiger', 'orange_tiger',
               'snow_white_tiger', 'white_tiger']

# ── CREATE MODELS FOLDER IF NOT EXISTS
os.makedirs(MODELS_PATH, exist_ok=True)
os.makedirs(TEST_IMAGES_PATH, exist_ok=True)

# ── VERIFY ALL PATHS EXIST
print('=' * 55)
print('PATH VERIFICATION REPORT')
print('=' * 55)

paths_to_check = {
    'Project Root'          : PROJECT_ROOT,
    'Dataset Folder'        : DATASET_PATH,
    'Tiger Images'          : TIGER_PATH,
    'No Tiger Images'       : NO_TIGER_PATH,
    'Roboflow Dataset'      : ROBOFLOW_PATH,
    'data.yaml'             : YAML_PATH,
    'Tiger Types Folder'    : TIGER_TYPES_PATH,
    'Models Folder'         : MODELS_PATH,
    'Test Images Folder'    : TEST_IMAGES_PATH,
}

all_good = True
for name, path in paths_to_check.items():
    exists = os.path.exists(path)
    status = '✅' if exists else '❌ MISSING'
    if not exists:
        all_good = False
    print(f'{status}  {name}')
    if not exists:
        print(f'       Expected at: {path}')

print('\n' + '=' * 55)
print('IMAGE COUNT REPORT')
print('=' * 55)

def count_images(folder):
    if not os.path.exists(folder):
        return 0
    exts = ('.jpg', '.jpeg', '.png', '.webp', '.bmp')
    return len([f for f in os.listdir(folder)
                if f.lower().endswith(exts)])

tiger_count    = count_images(TIGER_PATH)
no_tiger_count = count_images(NO_TIGER_PATH)
print(f'   Tiger images (YOLO training)   : {tiger_count}')
print(f'   No tiger images                : {no_tiger_count}')
print()

total_type_images = 0
for tiger_type in TIGER_TYPES:
    type_path  = f'{TIGER_TYPES_PATH}/{tiger_type}'
    type_count = count_images(type_path)
    total_type_images += type_count
    status = '✅' if type_count >= 40 else '⚠️  LOW'
    print(f'   {status}  {tiger_type:<22}: {type_count} images')

print(f'\n   Total tiger type images        : {total_type_images}')
print('=' * 55)

if all_good:
    print('\n✅ All paths verified. Ready to proceed!')
else:
    print('\n❌ Fix missing paths before continuing.')

"""---
## SECTION 2 — IMAGE QUALITY FILTER
### Cell 2.1 — Clean Bad Images Before Training
"""

# ============================================================
# CELL 2.1 — IMAGE QUALITY FILTER
# Automatically removes corrupt, too dark, too bright,
# or too blurry images before training
# ============================================================

import cv2
import numpy as np
import os
from PIL import Image

def assess_image_quality(image_path):
    """
    Returns (status, reason)
    status: 'GOOD' or 'BAD'
    """
    try:
        # Try opening with PIL first (catches corrupt files)
        pil_img = Image.open(image_path)
        pil_img.verify()

        # Reload after verify (verify closes the file)
        img = cv2.imread(image_path)
        if img is None:
            return 'BAD', 'Cannot read file'

        # Check minimum size
        h, w = img.shape[:2]
        if h < 64 or w < 64:
            return 'BAD', f'Too small ({w}x{h})'

        # Check brightness
        gray       = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        brightness = np.mean(gray)
        if brightness < 15:
            return 'BAD', f'Too dark (brightness={brightness:.1f})'
        if brightness > 245:
            return 'BAD', f'Too bright/overexposed (brightness={brightness:.1f})'

        # Check blur using Laplacian variance
        blur_score = cv2.Laplacian(gray, cv2.CV_64F).var()
        if blur_score < 10:
            return 'BAD', f'Too blurry (score={blur_score:.1f})'

        return 'GOOD', f'OK (brightness={brightness:.1f}, blur={blur_score:.1f})'

    except Exception as e:
        return 'BAD', f'Corrupt file: {str(e)[:50]}'


def clean_folder(folder_path, folder_name):
    exts = ('.jpg', '.jpeg', '.png', '.webp', '.bmp')
    images = [f for f in os.listdir(folder_path)
              if f.lower().endswith(exts)]
    good, bad = 0, 0
    bad_files = []
    for fname in images:
        fpath  = os.path.join(folder_path, fname)
        status, reason = assess_image_quality(fpath)
        if status == 'BAD':
            bad += 1
            bad_files.append((fname, reason))
        else:
            good += 1
    return good, bad, bad_files


print('=' * 55)
print('IMAGE QUALITY SCAN')
print('=' * 55)

folders_to_scan = [
    (TIGER_PATH,    'dataset/tiger'),
    (NO_TIGER_PATH, 'dataset/no_tiger'),
]
for ttype in TIGER_TYPES:
    folders_to_scan.append(
        (f'{TIGER_TYPES_PATH}/{ttype}', f'tiger_types/{ttype}')
    )

total_bad = 0
for folder_path, folder_name in folders_to_scan:
    if not os.path.exists(folder_path):
        continue
    good, bad, bad_files = clean_folder(folder_path, folder_name)
    total_bad += bad
    status = '✅' if bad == 0 else '⚠️'
    print(f'{status} {folder_name:<28}: {good} good, {bad} bad')
    for fname, reason in bad_files[:3]:   # show first 3 bad files
        print(f'      ↳ {fname}: {reason}')

print('=' * 55)
if total_bad == 0:
    print('✅ All images passed quality check!')
else:
    print(f'⚠️  {total_bad} bad images found.')
    print('   These will be automatically skipped during training.')
    print('   You can manually delete them for a cleaner dataset.')

"""---
## SECTION 3 — MODEL 1: YOLO TIGER DETECTOR
### Cell 3.1 — Prepare and Validate data.yaml
"""

# ============================================================
# CELL 3.1 — PREPARE data.yaml FOR YOLO TRAINING
# This fixes the paths inside data.yaml so YOLO
# can find your images correctly on Google Drive
# ============================================================

import yaml
import os

# Check if Roboflow dataset exists
if not os.path.exists(ROBOFLOW_PATH):
    print('❌ Roboflow dataset folder NOT FOUND!')
    print(f'   Expected at: {ROBOFLOW_PATH}')
    print()
    print('ACTION REQUIRED:')
    print('1. Extract your Roboflow ZIP file on your computer')
    print('2. Upload the extracted folder to Google Drive')
    print(f'3. Place it at: {ROBOFLOW_PATH}')
    print('4. Re-run this cell')
else:
    # Find data.yaml (search recursively)
    yaml_found = None
    for root, dirs, files in os.walk(ROBOFLOW_PATH):
        for f in files:
            if f == 'data.yaml':
                yaml_found = os.path.join(root, f)
                break

    if yaml_found is None:
        print('❌ data.yaml not found inside roboflow_dataset folder!')
        print('   Make sure you extracted the ZIP and uploaded all contents')
    else:
        YAML_PATH = yaml_found
        base_dir  = os.path.dirname(yaml_found)

        # Read current yaml
        with open(YAML_PATH, 'r') as f:
            data = yaml.safe_load(f)

        print('Original data.yaml content:')
        print(data)

        # Build correct absolute paths
        train_path = os.path.join(base_dir, 'train', 'images')
        valid_path = os.path.join(base_dir, 'valid', 'images')
        test_path  = os.path.join(base_dir, 'test',  'images')

        # Update yaml with absolute paths
        updated_data = {
            'train' : train_path,
            'val'   : valid_path,
            'test'  : test_path,
            'nc'    : 1,
            'names' : ['tiger']
        }

        with open(YAML_PATH, 'w') as f:
            yaml.dump(updated_data, f, default_flow_style=False)

        print('\n✅ data.yaml updated with correct paths!')
        print('\nUpdated content:')
        with open(YAML_PATH, 'r') as f:
            print(f.read())

        # Verify image folders exist
        print('Verifying image folders:')
        for split, path in [('train', train_path),
                             ('valid', valid_path),
                             ('test',  test_path)]:
            if os.path.exists(path):
                n = len(os.listdir(path))
                print(f'  ✅ {split}: {n} images at {path}')
            else:
                print(f'  ❌ {split}: folder not found at {path}')

"""### Cell 3.2 — Train YOLO Tiger Detector
> ⏱️ This takes approximately **30–50 minutes**. Do NOT close the browser tab.
"""

# ============================================================
# CELL 3.2 — TRAIN YOLO TIGER DETECTOR
# Runtime: ~30-50 minutes on T4 GPU
# Do NOT close the browser while this is running
# ============================================================

from ultralytics import YOLO
import os

print('=' * 55)
print('STARTING YOLO TRAINING — MODEL 1')
print('=' * 55)
print('Model  : YOLOv8s (small — best for your dataset size)')
print('Epochs : 100')
print('Task   : Detect and count tigers in images')
print()
print('Training progress will appear below.')
print('Watch the mAP50 value — it should rise toward 0.75+')
print('=' * 55)

# Load pretrained YOLOv8s model (small version)
# s = better accuracy than nano (n) for your dataset size
model = YOLO('yolov8s.pt')

# Train
results = model.train(
    data        = YAML_PATH,
    epochs      = 100,
    imgsz       = 640,
    batch       = 8,          # reduced for Drive I/O speed
    patience    = 20,         # stop if no improvement for 20 epochs
    save        = True,
    save_period = 10,         # save checkpoint every 10 epochs
    conf        = 0.25,       # confidence threshold during training
    iou         = 0.5,        # IOU threshold (NMS)
    optimizer   = 'AdamW',    # better optimizer for small datasets
    lr0         = 0.001,      # initial learning rate
    augment     = True,       # enable built-in augmentation
    mosaic      = 1.0,        # mosaic augmentation
    mixup       = 0.1,        # mixup augmentation
    degrees     = 15.0,       # rotation augmentation
    fliplr      = 0.5,        # horizontal flip probability
    project     = MODELS_PATH,
    name        = 'tiger_detector',
    exist_ok    = True,
    verbose     = True,
    device      = 0           # use GPU (device=0)
)

print('\n' + '=' * 55)
print('✅ YOLO TRAINING COMPLETE!')
print('=' * 55)
print(f'Best model saved at: {YOLO_MODEL_PATH}')
print()
print('Training Summary:')
print(f'  Best mAP@50   : {results.results_dict.get("metrics/mAP50(B)", 0):.3f}')
print(f'  Best Precision: {results.results_dict.get("metrics/precision(B)", 0):.3f}')
print(f'  Best Recall   : {results.results_dict.get("metrics/recall(B)", 0):.3f}')

"""### Cell 3.3 — Evaluate YOLO and Show Training Results"""

# ============================================================
# CELL 3.3 — EVALUATE YOLO MODEL + SHOW TRAINING GRAPHS
# ============================================================

from ultralytics import YOLO
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

# Load best trained model
yolo_model = YOLO(YOLO_MODEL_PATH)

# Evaluate on test split
print('Running evaluation on test set...')
metrics = yolo_model.val(data=YAML_PATH, split='test', verbose=False)

map50      = metrics.box.map50
precision  = metrics.box.mp
recall     = metrics.box.mr

print('\n' + '=' * 55)
print('MODEL 1 — YOLO EVALUATION RESULTS')
print('=' * 55)
print(f'  mAP@50    : {map50:.3f}   (target: > 0.75)')
print(f'  Precision : {precision:.3f}   (target: > 0.80)')
print(f'  Recall    : {recall:.3f}   (target: > 0.75)')
print()

# Interpret results
if map50 >= 0.75:
    print('✅ EXCELLENT — Model is ready for use!')
elif map50 >= 0.60:
    print('⚠️  ACCEPTABLE — Model works but could be better.')
    print('   Tip: Collect more labeled images to improve accuracy.')
else:
    print('❌ NEEDS IMPROVEMENT — mAP@50 is below 0.60')
    print('   Tip: Check your labels in Roboflow for errors.')
    print('   Tip: Make sure bounding boxes are tight around tigers.')

print('=' * 55)

# Show training plots
results_dir = f'{MODELS_PATH}/tiger_detector'
plot_files  = ['results.png', 'confusion_matrix.png', 'PR_curve.png']

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('YOLO Training Results', fontsize=16, fontweight='bold')

for ax, plot_file in zip(axes, plot_files):
    plot_path = os.path.join(results_dir, plot_file)
    if os.path.exists(plot_path):
        img = mpimg.imread(plot_path)
        ax.imshow(img)
        ax.set_title(plot_file.replace('.png', '').replace('_', ' ').title())
        ax.axis('off')
    else:
        ax.text(0.5, 0.5, f'{plot_file}\nnot found',
                ha='center', va='center', transform=ax.transAxes)
        ax.axis('off')

plt.tight_layout()
plt.show()
print('\n✅ Evaluation complete. Proceed to Section 4.')

"""---
## SECTION 4 — MODEL 2: TIGER TYPE CLASSIFIER
### Cell 4.1 — Prepare Tiger Type Dataset with Augmentation
"""

# ============================================================
# CELL 4.1 — PREPARE TIGER TYPE DATASET
# Applies augmentation to grow your small dataset
# 329 images → ~2000+ training samples automatically
# ============================================================

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np

IMG_SIZE   = (300, 300)    # EfficientNetB3 optimal input size
BATCH_SIZE = 16            # reduced for Google Drive I/O

# Augmentation for training
# This artificially multiplies your images with variations
train_datagen = ImageDataGenerator(
    rescale            = 1./255,
    rotation_range     = 25,
    width_shift_range  = 0.2,
    height_shift_range = 0.2,
    horizontal_flip    = True,
    zoom_range         = 0.25,
    brightness_range   = [0.7, 1.3],
    shear_range        = 0.2,
    fill_mode          = 'nearest',
    validation_split   = 0.2       # 80% train, 20% validate
)

# NO augmentation for validation (we want real performance)
val_datagen = ImageDataGenerator(
    rescale          = 1./255,
    validation_split = 0.2
)

# Load training data
train_data = train_datagen.flow_from_directory(
    TIGER_TYPES_PATH,
    target_size  = IMG_SIZE,
    batch_size   = BATCH_SIZE,
    class_mode   = 'categorical',
    subset       = 'training',
    shuffle      = True,
    seed         = 42
)

# Load validation data
val_data = val_datagen.flow_from_directory(
    TIGER_TYPES_PATH,
    target_size  = IMG_SIZE,
    batch_size   = BATCH_SIZE,
    class_mode   = 'categorical',
    subset       = 'validation',
    shuffle      = False,
    seed         = 42
)

# Class mapping
CLASS_INDICES = train_data.class_indices
CLASS_NAMES   = {v: k for k, v in CLASS_INDICES.items()}
NUM_CLASSES   = len(CLASS_INDICES)

print('=' * 55)
print('DATASET PREPARATION COMPLETE')
print('=' * 55)
print(f'  Training images   : {train_data.samples}')
print(f'  Validation images : {val_data.samples}')
print(f'  Number of classes : {NUM_CLASSES}')
print()
print('  Class mapping:')
for name, idx in sorted(CLASS_INDICES.items(), key=lambda x: x[1]):
    count = len(os.listdir(f'{TIGER_TYPES_PATH}/{name}'))
    print(f'    [{idx}] {name:<22}: {count} images')
print('=' * 55)

# Show sample images from each class
print('\nSample images from each tiger type:')
fig, axes = plt.subplots(1, NUM_CLASSES, figsize=(20, 4))
fig.suptitle('Tiger Types — Training Samples', fontsize=14, fontweight='bold')

for idx, (tiger_type, class_idx) in enumerate(sorted(CLASS_INDICES.items(),
                                               key=lambda x: x[1])):
    type_folder = f'{TIGER_TYPES_PATH}/{tiger_type}'
    images      = [f for f in os.listdir(type_folder)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    if images:
        sample_path = os.path.join(type_folder, images[0])
        img         = plt.imread(sample_path)
        axes[idx].imshow(img)
        axes[idx].set_title(tiger_type.replace('_', '\n'), fontsize=10)
        axes[idx].axis('off')

plt.tight_layout()
plt.show()
print('\n✅ Dataset ready. Proceed to Cell 4.2 to build the model.')

"""### Cell 4.2 — Build EfficientNetB3 Classifier"""

# ============================================================
# CELL 4.2 — BUILD EFFICIENTNETB3 TIGER TYPE CLASSIFIER
# Uses Transfer Learning — borrows knowledge from a model
# already trained on 1.2 million images
# ============================================================

import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB3
from tensorflow.keras import layers, models, regularizers

# Load EfficientNetB3 pretrained on ImageNet
# include_top=False removes the final classification layer
# so we can add our own 5-class tiger type layer
base_model = EfficientNetB3(
    input_shape = (300, 300, 3),
    include_top = False,
    weights     = 'imagenet'
)

# Freeze the base model
# We keep Google's learned knowledge intact
# and only train our new top layers
base_model.trainable = False

# Build the complete model
inputs = tf.keras.Input(shape=(300, 300, 3))
x      = base_model(inputs, training=False)
x      = layers.GlobalAveragePooling2D()(x)
x      = layers.BatchNormalization()(x)
x      = layers.Dense(
             512,
             activation='relu',
             kernel_regularizer=regularizers.l2(0.001)
         )(x)
x      = layers.Dropout(0.5)(x)
x      = layers.Dense(
             256,
             activation='relu',
             kernel_regularizer=regularizers.l2(0.001)
         )(x)
x      = layers.Dropout(0.4)(x)
outputs = layers.Dense(NUM_CLASSES, activation='softmax')(x)

classifier_model = tf.keras.Model(inputs, outputs)

# Compile with AdamW optimizer
classifier_model.compile(
    optimizer = tf.keras.optimizers.AdamW(learning_rate=0.001),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy',
                 tf.keras.metrics.TopKCategoricalAccuracy(
                     k=2, name='top2_accuracy')]
)

# Print model summary
total_params     = classifier_model.count_params()
trainable_params = sum([tf.size(w).numpy()
                        for w in classifier_model.trainable_weights])

print('=' * 55)
print('MODEL 2 — EFFICIENTNETB3 ARCHITECTURE')
print('=' * 55)
print(f'  Total parameters     : {total_params:,}')
print(f'  Trainable parameters : {trainable_params:,}')
print(f'  Frozen parameters    : {total_params - trainable_params:,}')
print(f'  Input shape          : (300, 300, 3)')
print(f'  Output classes       : {NUM_CLASSES}')
print(f'  Output class names   : {list(CLASS_INDICES.keys())}')
print('=' * 55)
print('\n✅ Model built successfully. Proceed to Cell 4.3 to train.')

"""### Cell 4.3 — Train Tiger Type Classifier
> ⏱️ Phase 1 takes ~20 minutes, Phase 2 (fine-tuning) takes ~30 minutes.
"""

# ============================================================
# CELL 4.3 — TRAIN TIGER TYPE CLASSIFIER
# Two-phase training:
# Phase 1: Train only top layers (fast)
# Phase 2: Fine-tune entire model (more accurate)
# Total runtime: ~45-60 minutes
# ============================================================

import tensorflow as tf
import os

# ── CALLBACKS ──────────────────────────────────────────────

# Save best model automatically
checkpoint = tf.keras.callbacks.ModelCheckpoint(
    EFFNET_MODEL_PATH,
    monitor         = 'val_accuracy',
    save_best_only  = True,
    mode            = 'max',
    verbose         = 1
)

# Stop early if no improvement
early_stop = tf.keras.callbacks.EarlyStopping(
    monitor              = 'val_accuracy',
    patience             = 15,
    restore_best_weights = True,
    verbose              = 1
)

# Reduce learning rate when stuck
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor  = 'val_loss',
    factor   = 0.5,
    patience = 5,
    min_lr   = 1e-7,
    verbose  = 1
)

# ── PHASE 1: TRAIN TOP LAYERS ONLY ─────────────────────────
print('=' * 55)
print('PHASE 1 — TRAINING TOP LAYERS')
print('Base model is FROZEN')
print('Expected runtime: ~20 minutes')
print('=' * 55)

history_phase1 = classifier_model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 30,
    callbacks       = [checkpoint, early_stop, reduce_lr],
    verbose         = 1
)

phase1_best_acc = max(history_phase1.history['val_accuracy'])
print(f'\n✅ Phase 1 complete! Best validation accuracy: {phase1_best_acc:.3f}')

# ── PHASE 2: FINE-TUNE ENTIRE MODEL ────────────────────────
print('\n' + '=' * 55)
print('PHASE 2 — FINE TUNING ENTIRE MODEL')
print('Unfreezing top 30 layers of EfficientNetB3')
print('Expected runtime: ~30 minutes')
print('=' * 55)

# Unfreeze the top layers of the base model
base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

# Recompile with much lower learning rate for fine-tuning
classifier_model.compile(
    optimizer = tf.keras.optimizers.AdamW(learning_rate=1e-5),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy',
                 tf.keras.metrics.TopKCategoricalAccuracy(
                     k=2, name='top2_accuracy')]
)

history_phase2 = classifier_model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 50,
    callbacks       = [checkpoint, early_stop, reduce_lr],
    verbose         = 1
)

phase2_best_acc = max(history_phase2.history['val_accuracy'])

print('\n' + '=' * 55)
print('✅ TRAINING COMPLETE!')
print('=' * 55)
print(f'  Phase 1 best accuracy : {phase1_best_acc:.3f} ({phase1_best_acc*100:.1f}%)')
print(f'  Phase 2 best accuracy : {phase2_best_acc:.3f} ({phase2_best_acc*100:.1f}%)')
print(f'  Model saved at        : {EFFNET_MODEL_PATH}')

"""### Cell 4.4 — Evaluate Classifier and Show Confusion Matrix"""

# ============================================================
# CELL 4.4 — EVALUATE TIGER TYPE CLASSIFIER
# Shows accuracy, confusion matrix, and training curves
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf

# Load best saved model
best_classifier = tf.keras.models.load_model(EFFNET_MODEL_PATH)

# Evaluate on validation set
val_loss, val_acc, val_top2 = best_classifier.evaluate(
    val_data, verbose=0
)

print('=' * 55)
print('MODEL 2 — EVALUATION RESULTS')
print('=' * 55)
print(f'  Validation Accuracy  : {val_acc:.3f} ({val_acc*100:.1f}%)')
print(f'  Top-2 Accuracy       : {val_top2:.3f} ({val_top2*100:.1f}%)')
print(f'  Validation Loss      : {val_loss:.3f}')
print()

if val_acc >= 0.85:
    print('✅ EXCELLENT — Model ready for deployment!')
elif val_acc >= 0.70:
    print('⚠️  GOOD — Acceptable for prototype. More data will improve this.')
else:
    print('❌ NEEDS IMPROVEMENT — Consider collecting more images per tiger type.')

print('=' * 55)

# Generate predictions for confusion matrix
val_data.reset()
y_pred_probs = best_classifier.predict(val_data, verbose=0)
y_pred       = np.argmax(y_pred_probs, axis=1)
y_true       = val_data.classes
class_labels = list(CLASS_NAMES[i] for i in sorted(CLASS_NAMES.keys()))
short_labels = [l.replace('_tiger', '').replace('_', ' ').title()
                for l in class_labels]

# Plot training curves and confusion matrix
fig, axes = plt.subplots(1, 3, figsize=(22, 7))
fig.suptitle('Model 2 — EfficientNetB3 Results', fontsize=16, fontweight='bold')

# Combine both training phases
all_acc     = (history_phase1.history['accuracy'] +
               history_phase2.history['accuracy'])
all_val_acc = (history_phase1.history['val_accuracy'] +
               history_phase2.history['val_accuracy'])
all_loss    = (history_phase1.history['loss'] +
               history_phase2.history['loss'])
all_val_loss= (history_phase1.history['val_loss'] +
               history_phase2.history['val_loss'])

# Plot 1 — Accuracy curve
axes[0].plot(all_acc,     label='Train Accuracy', color='blue')
axes[0].plot(all_val_acc, label='Val Accuracy',   color='orange')
axes[0].axvline(len(history_phase1.history['accuracy']),
                color='red', linestyle='--', label='Fine-tune starts')
axes[0].set_title('Accuracy Over Epochs')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Plot 2 — Loss curve
axes[1].plot(all_loss,     label='Train Loss', color='blue')
axes[1].plot(all_val_loss, label='Val Loss',   color='orange')
axes[1].axvline(len(history_phase1.history['loss']),
                color='red', linestyle='--', label='Fine-tune starts')
axes[1].set_title('Loss Over Epochs')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

# Plot 3 — Confusion matrix
cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=short_labels,
            yticklabels=short_labels,
            ax=axes[2])
axes[2].set_title('Confusion Matrix')
axes[2].set_xlabel('Predicted')
axes[2].set_ylabel('Actual')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Print per-class report
print('\nPer-class Classification Report:')
print(classification_report(y_true, y_pred, target_names=short_labels))
print('\n✅ Evaluation complete. Proceed to Section 5.')

"""---
## SECTION 5 — COMPLETE PIPELINE
### Cell 5.1 — Build the Full Tiger Analysis Pipeline
"""

# ============================================================
# CELL 5.1 — COMPLETE TIGER ANALYSIS PIPELINE
# This function takes ONE image and returns:
# - How many tigers are in it
# - What type each tiger is
# - Confidence scores
# ============================================================

import cv2
import numpy as np
import tensorflow as tf
from ultralytics import YOLO
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import os

# Load both trained models
print('Loading trained models...')
yolo_model       = YOLO(YOLO_MODEL_PATH)
classifier_model = tf.keras.models.load_model(EFFNET_MODEL_PATH)
print('✅ Both models loaded successfully!')

# Tiger type display names and colors for visualization
TYPE_DISPLAY_NAMES = {
    'black_tiger'      : 'Black Tiger',
    'golden_tiger'     : 'Golden Tiger',
    'orange_tiger'     : 'Orange Tiger',
    'snow_white_tiger' : 'Snow White Tiger',
    'white_tiger'      : 'White Tiger'
}

BOX_COLORS = {
    'black_tiger'      : (50,  50,  50),
    'golden_tiger'     : (255, 215, 0),
    'orange_tiger'     : (255, 140, 0),
    'snow_white_tiger' : (200, 200, 255),
    'white_tiger'      : (255, 255, 255)
}


def preprocess_for_camera_trap(image_path):
    """
    Handles common camera trap image issues:
    - IR grayscale night shots → converts to RGB
    - Dark images → brightness boost
    - Low contrast → contrast enhancement
    """
    img = Image.open(image_path)

    # Convert IR grayscale to RGB
    if img.mode != 'RGB':
        img = img.convert('RGB')

    img_array  = np.array(img)
    brightness = np.mean(img_array)

    # Auto brightness boost for dark images
    if brightness < 60:
        from PIL import ImageEnhance
        enhancer = ImageEnhance.Brightness(img)
        img      = enhancer.enhance(2.0)
        enhancer = ImageEnhance.Contrast(img)
        img      = enhancer.enhance(1.5)
    elif brightness < 100:
        from PIL import ImageEnhance
        enhancer = ImageEnhance.Brightness(img)
        img      = enhancer.enhance(1.4)
        enhancer = ImageEnhance.Contrast(img)
        img      = enhancer.enhance(1.2)

    return img


def classify_tiger_crop(crop_array):
    """
    Takes a cropped tiger image (numpy array)
    Returns (tiger_type, confidence)
    """
    # Resize to EfficientNetB3 input size
    crop_pil    = Image.fromarray(crop_array)
    crop_resize = crop_pil.resize((300, 300))
    crop_norm   = np.array(crop_resize) / 255.0
    crop_batch  = np.expand_dims(crop_norm, axis=0)

    # Predict
    predictions = classifier_model.predict(crop_batch, verbose=0)
    pred_idx    = np.argmax(predictions[0])
    confidence  = float(predictions[0][pred_idx])
    tiger_type  = CLASS_NAMES[pred_idx]

    return tiger_type, confidence, predictions[0]


def analyze_image(image_path,
                  conf_threshold = 0.35,
                  iou_threshold  = 0.5,
                  show_result    = True):
    """
    Main pipeline function.
    Takes an image path and returns complete tiger analysis.

    Parameters:
    - image_path    : path to the image file
    - conf_threshold: YOLO confidence threshold (0.0 to 1.0)
                      increase if seeing too many false detections
                      decrease if missing real tigers
    - iou_threshold : overlap threshold for duplicate removal
                      increase if seeing duplicate boxes on same tiger
    - show_result   : whether to display the annotated image

    Returns: dict with detection results
    """
    filename = os.path.basename(image_path)

    # ── STEP 1: Image Quality Check ────────────────────────
    # The custom preprocessing was interfering with YOLO's detection.
    # YOLO will now handle its own image loading and initial preprocessing.
    # We still run preprocess_for_camera_trap to get img_pil for subsequent
    # steps like classification and display, but YOLO will operate on the raw image path.
    original_img_pil = Image.open(image_path) # Load original for display/further processing
    img_pil          = preprocess_for_camera_trap(image_path)
    img_array        = np.array(img_pil)
    brightness       = np.mean(img_array)

    quality_issues = []
    if brightness < 20:
        quality_issues.append('Very dark image')
    if brightness > 240:
        quality_issues.append('Overexposed image')

    gray       = cv2.cvtColor(img_array, cv2.COLOR_RGB2GRAY)
    blur_score = cv2.Laplacian(gray, cv2.CV_64F).var()
    if blur_score < 10:
        quality_issues.append(f'Very blurry (score={blur_score:.1f})')

    # ── STEP 2: Tiger Detection with YOLO ──────────────────
    results = yolo_model(
        image_path, # Changed from img_pil to image_path to use YOLO's native loading
        conf    = conf_threshold,
        iou     = iou_threshold,
        verbose = False
    )

    detections  = []
    result      = results[0]
    boxes       = result.boxes
    annotated   = np.array(original_img_pil.copy()) # Use original image for annotation

    # ── STEP 3: Classify Each Detected Tiger ───────────────
    for i, box in enumerate(boxes):
        # Get bounding box coordinates
        x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
        det_conf        = float(box.conf[0])

        # Crop the tiger from the image
        # Add small padding around the box
        pad  = 10
        h, w = img_array.shape[:2]
        cx1  = max(0, x1 - pad)
        cy1  = max(0, y1 - pad)
        cx2  = min(w, x2 + pad)
        cy2  = min(h, y2 + pad)
        # Use img_array for classification as it has preprocessing for quality (brightness/contrast)
        crop = img_array[cy1:cy2, cx1:cx2]

        # Classify the cropped tiger
        if crop.size > 0:
            tiger_type, type_conf, all_probs = classify_tiger_crop(crop)
        else:
            tiger_type, type_conf = 'unknown', 0.0
            all_probs = np.zeros(NUM_CLASSES)

        # Determine detection quality
        area        = (x2 - x1) * (y2 - y1)
        total_area  = img_array.shape[0] * img_array.shape[1]
        area_ratio  = area / total_area

        if area_ratio > 0.15:
            visibility = 'full'
        elif area_ratio > 0.05:
            visibility = 'partial'
        else:
            visibility = 'trace'

        detection = {
            'tiger_id'    : i + 1,
            'type'        : tiger_type,
            'display_name': TYPE_DISPLAY_NAMES.get(tiger_type, tiger_type),
            'det_conf'    : det_conf,
            'type_conf'   : type_conf,
            'visibility'  : visibility,
            'bbox'        : (x1, y1, x2, y2),
            'all_probs'   : all_probs
        }
        detections.append(detection)

        # ── Draw on image ──────────────────────────────────
        color = BOX_COLORS.get(tiger_type, (0, 255, 0))

        # Draw bounding box
        cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 3)

        # Draw label background
        label     = f'Tiger {i+1}: {TYPE_DISPLAY_NAMES.get(tiger_type, tiger_type)}'
        sub_label = f'Det:{det_conf:.0%} Type:{type_conf:.0%} [{visibility}]'

        (lw, lh), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(annotated,
                      (x1, y1 - lh - 25),
                      (x1 + max(lw, 200), y1),
                      color, -1)

        # Draw text
        text_color = (0, 0, 0) if tiger_type in ['white_tiger',
                                                  'snow_white_tiger',
                                                  'golden_tiger'] else (255, 255, 255)
        cv2.putText(annotated, label,
                    (x1 + 3, y1 - 13),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, text_color, 2)
        cv2.putText(annotated, sub_label,
                    (x1 + 3, y1 - 2),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.4, text_color, 1)

    # ── STEP 4: Show Results ───────────────────────────────
    tiger_count = len(detections)

    if show_result:
        fig, axes = plt.subplots(1, 2, figsize=(20, 8))
        fig.suptitle(f'Tiger Analysis: {filename}',
                     fontsize=14, fontweight='bold')

        # Original image
        axes[0].imshow(original_img_pil) # Display original untouched image
        axes[0].set_title('Original Image')
        axes[0].axis('off')

        # Annotated image
        axes[1].imshow(annotated)
        axes[1].set_title(f'Detection Result — {tiger_count} Tiger(s) Found')
        axes[1].axis('off')

        plt.tight_layout()
        plt.show()

        # Print text summary
        print('\n' + '─' * 50)
        print(f'FILE      : {filename}')
        print(f'TIGERS    : {tiger_count}')
        if quality_issues:
            print(f'QUALITY   : ⚠️  {" | ".join(quality_issues)}')
        else:
            print(f'QUALITY   : ✅ Good')
        print('─' * 50)

        for d in detections:
            vis_icon = {'full': '🐯', 'partial': '🐯½', 'trace': '🐾'}
            print(f'  Tiger {d["tiger_id"]} : {d["display_name"]}')
            print(f'           Visibility   : {vis_icon.get(d["visibility"], "?")} {d["visibility"]}')
            print(f'           Detection    : {d["det_conf"]:.1%} confidence')
            print(f'           Type         : {d["type_conf"]:.1%} confidence')

            # Show top 3 type probabilities
            top3_idx = np.argsort(d['all_probs'])[::-1][:3]
            print(f'           Top 3 types  :')
            for rank, idx in enumerate(top3_idx, 1):
                tname = CLASS_NAMES[idx]
                tprob = d['all_probs'][idx]
                bar   = '█' * int(tprob * 20)
                print(f'             {rank}. {TYPE_DISPLAY_NAMES.get(tname, tname):<20}: {bar:<20} {tprob:.1%}')
        print('─' * 50)

    return {
        'filename'      : filename,
        'tiger_count'   : tiger_count,
        'detections'    : detections,
        'quality_issues': quality_issues,
        'blur_score'    : blur_score,
        'brightness'    : brightness
    }


print('✅ Pipeline function loaded successfully!')
print('   Proceed to Cell 5.2 to test on a single image.')

"""### Cell 5.2 — Test on a Single Image"""

# ============================================================
# CELL 5.2 — TEST ON A SINGLE IMAGE
# Place test images in: Tiger_Project/test_images/
# ============================================================

import os

# Get all images in test_images folder
test_exts   = ('.jpg', '.jpeg', '.png', '.webp', '.bmp')
test_images = [f for f in os.listdir(TEST_IMAGES_PATH)
               if f.lower().endswith(test_exts)]

if not test_images:
    print('❌ No images found in test_images folder!')
    print(f'   Please upload at least one tiger image to:')
    print(f'   {TEST_IMAGES_PATH}')
else:
    print(f'Found {len(test_images)} test image(s):')
    for i, img in enumerate(test_images):
        print(f'  [{i}] {img}')

    print()

    # Test on the specified image (index 8 for '000004.jpg')
    # Change the index to test a different image
    test_image_path = os.path.join(TEST_IMAGES_PATH, test_images[8])

    print(f'Testing on: {test_images[8]}')
    print()

    # ── THRESHOLD SETTINGS ────────────────────────────────
    # If model detects TOO MANY tigers (duplicates):
    #   → Increase conf_threshold (try 0.45, 0.5, 0.6)
    #   → Increase iou_threshold  (try 0.5, 0.6, 0.7)
    # If model detects TOO FEW tigers (misses real ones):
    #   → Decrease conf_threshold (try 0.25, 0.2)
    # ──────────────────────────────────────────────────────

    result = analyze_image(
        test_image_path,
        conf_threshold = 0.15,   # adjust if seeing duplicates
        iou_threshold  = 0.7,    # adjust if seeing duplicates
        show_result    = True
    )

"""### Cell 5.3 — Threshold Tuning (Fix Duplicate Detections)"""

# ============================================================
# CELL 5.3 — THRESHOLD TUNING
# Run this ONLY if you are seeing duplicate boxes
# (e.g., 5 boxes on 1 tiger)
# This finds the best threshold combination for your images
# ============================================================

from ultralytics import YOLO
import os

# Use your test image
test_image_path = os.path.join(TEST_IMAGES_PATH, test_images[0])
EXPECTED_COUNT  = 2   # ← Change this to the REAL number of
                      #   tigers in your test image

yolo_model    = YOLO(YOLO_MODEL_PATH)
conf_values   = [0.1, 0.15, 0.25, 0.35, 0.45, 0.50, 0.55, 0.60, 0.70]
iou_values    = [0.30, 0.40, 0.50, 0.60, 0.70]

print('=' * 65)
print('THRESHOLD TUNING RESULTS')
print(f'Expected tiger count: {EXPECTED_COUNT}')
print('=' * 65)
print(f'{"conf":<8} {"iou":<8} {"detected":<12} {"verdict"}')
print('-' * 65)

best_conf, best_iou = 0.35, 0.5

for conf in conf_values:
    for iou in iou_values:
        res   = yolo_model(
            test_image_path,
            conf    = conf,
            iou     = iou,
            verbose = False
        )
        count = len(res[0].boxes)

        if count == EXPECTED_COUNT:
            verdict    = '✅ PERFECT'
            best_conf  = conf
            best_iou   = iou
        elif count < EXPECTED_COUNT:
            verdict = f'⬇️  Under-detecting (missing {EXPECTED_COUNT - count})'
        else:
            verdict = f'⬆️  Over-detecting  (+{count - EXPECTED_COUNT} extra)'

        print(f'{conf:<8} {iou:<8} {count:<12} {verdict}')

print('=' * 65)
print(f'\n✅ Recommended settings:')
print(f'   conf_threshold = {best_conf}')
print(f'   iou_threshold  = {best_iou}')
print()
print('Use these values in Cell 5.2 and Cell 5.4')

"""### Cell 5.4 — Analyze ALL Images and Generate Population Report"""

# ============================================================
# CELL 5.4 — ANALYZE ALL IMAGES + GENERATE POPULATION REPORT
# This is the FINAL STEP — the complete forest official report
# Upload ALL forest camera trap images to test_images/ folder
# then run this cell
# ============================================================

import os
import json
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

# ── SETTINGS (use values from Cell 5.3) ────────────────────
CONF_THRESHOLD = 0.15    # ← update from Cell 5.3 if needed
IOU_THRESHOLD  = 0.7    # ← update from Cell 5.3 if needed
# ───────────────────────────────────────────────────────────

test_exts   = ('.jpg', '.jpeg', '.png', '.webp', '.bmp')
all_images  = sorted([f for f in os.listdir(TEST_IMAGES_PATH)
                      if f.lower().endswith(test_exts)])

if not all_images:
    print('❌ No images found in test_images folder!')
    print(f'   Upload images to: {TEST_IMAGES_PATH}')
else:
    print(f'Processing {len(all_images)} images...')
    print('This may take a few minutes depending on image count.')
    print()

    # ── PROCESS ALL IMAGES ─────────────────────────────────
    all_results     = []
    type_counts     = {t: 0 for t in TIGER_TYPES}
    unusable_images = []
    no_tiger_images = []
    tiger_images    = []
    total_detections= 0

    for i, fname in enumerate(all_images):
        fpath = os.path.join(TEST_IMAGES_PATH, fname)
        print(f'  [{i+1:3d}/{len(all_images)}] {fname}', end=' ... ')

        try:
            result = analyze_image(
                fpath,
                conf_threshold = CONF_THRESHOLD,
                iou_threshold  = IOU_THRESHOLD,
                show_result    = False      # suppress individual displays
            )
            all_results.append(result)

            if result['quality_issues'] and result['tiger_count'] == 0:
                unusable_images.append(fname)
                print(f'⚠️  UNUSABLE ({result["quality_issues"][0]})')
            elif result['tiger_count'] == 0:
                no_tiger_images.append(fname)
                print('— No tiger')
            else:
                tiger_images.append(fname)
                total_detections += result['tiger_count']
                types_in_image = [d['display_name'] for d in result['detections']]
                print(f'🐯 {result["tiger_count"]} tiger(s): {", ".join(types_in_image)}')

                for det in result['detections']:
                    ttype = det['type']
                    if ttype in type_counts:
                        type_counts[ttype] += 1

        except Exception as e:
            print(f'❌ ERROR: {str(e)[:60]}')
            unusable_images.append(fname)

    # ── GENERATE REPORT ────────────────────────────────────
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    total_img = len(all_images)

    report_lines = [
        '=' * 60,
        '       FOREST TIGER POPULATION REPORT',
        '=' * 60,
        f'  Generated     : {timestamp}',
        f'  Models Used   : YOLOv8s + EfficientNetB3',
        f'  Conf Threshold: {CONF_THRESHOLD}',
        f'  IOU Threshold : {IOU_THRESHOLD}',
        '=' * 60,
        '',
        '  IMAGE PROCESSING SUMMARY',
        '  ' + '-' * 40,
        f'  Total images processed : {total_img}',
        f'  Images with tigers     : {len(tiger_images)}',
        f'  Images with no tiger   : {len(no_tiger_images)}',
        f'  Unusable images        : {len(unusable_images)}',
        '',
        '  TIGER DETECTION SUMMARY',
        '  ' + '-' * 40,
        f'  Total detections       : {total_detections}',
        '',
        '  TIGER TYPE BREAKDOWN',
        '  ' + '-' * 40,
    ]

    for ttype, count in sorted(type_counts.items(),
                                key=lambda x: x[1], reverse=True):
        pct   = (count / total_detections * 100) if total_detections > 0 else 0
        bar   = '█' * int(pct / 5)
        dname = TYPE_DISPLAY_NAMES.get(ttype, ttype)
        report_lines.append(
            f'  {dname:<22}: {count:3d} ({pct:5.1f}%) {bar}'
        )

    report_lines += [
        '',
        '  UNUSABLE IMAGES (quality issues)',
        '  ' + '-' * 40,
    ]
    if unusable_images:
        for f in unusable_images[:10]:
            report_lines.append(f'  • {f}')
        if len(unusable_images) > 10:
            report_lines.append(f'  ... and {len(unusable_images)-10} more')
    else:
        report_lines.append('  None — all images were usable!')

    report_lines += [
        '',
        '  NOTES',
        '  ' + '-' * 40,
        '  * Detection counts multiple sightings of same tiger.',
        '  * Individual tiger Re-ID requires stripe matching',
        '    (advanced feature — Phase 2 development).',
        '  * Low confidence detections flagged as partial/trace.',
        '  * Results based on prototype model trained on',
        f'    329 labeled images. Accuracy improves with',
        '    official forest camera trap training data.',
        '',
        '=' * 60,
        '  END OF REPORT',
        '=' * 60,
    ]

    report_text = '\n'.join(report_lines)

    # Print report
    print('\n\n')
    print(report_text)

    # Save report to Google Drive
    with open(REPORT_PATH, 'w') as f:
        f.write(report_text)
    print(f'\n✅ Report saved to: {REPORT_PATH}')

    # ── VISUALISE REPORT ───────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.suptitle('Tiger Population Report — Visual Summary',
                 fontsize=16, fontweight='bold')

    # Chart 1 — Image categories pie chart
    pie_labels = ['Tiger Images', 'No Tiger', 'Unusable']
    pie_values = [len(tiger_images), len(no_tiger_images), len(unusable_images)]
    pie_colors = ['#FF8C00', '#4CAF50', '#9E9E9E']
    axes[0].pie(pie_values, labels=pie_labels, colors=pie_colors,
                autopct='%1.1f%%', startangle=90)
    axes[0].set_title('Image Categories')

    # Chart 2 — Tiger type bar chart
    types_with_data  = {k: v for k, v in type_counts.items() if v > 0}
    if types_with_data:
        short_names = [TYPE_DISPLAY_NAMES.get(k, k).replace(' Tiger', '')
                       for k in types_with_data.keys()]
        bar_colors  = ['#FF8C00', '#FFD700', '#1a1a1a', '#F5F5F5', '#EEEEEE']
        bars = axes[1].bar(short_names, list(types_with_data.values()),
                           color=bar_colors[:len(types_with_data)],
                           edgecolor='black', linewidth=1.5)
        axes[1].set_title('Tiger Types Detected')
        axes[1].set_ylabel('Count')
        axes[1].tick_params(axis='x', rotation=30)
        for bar, val in zip(bars, types_with_data.values()):
            axes[1].text(bar.get_x() + bar.get_width()/2., bar.get_height(),
                         str(val), ha='center', va='bottom', fontweight='bold')
    else:
        axes[1].text(0.5, 0.5, 'No tigers\ndetected',
                     ha='center', va='center', transform=axes[1].transAxes,
                     fontsize=14)
        axes[1].axis('off')

    # Chart 3 — Summary stats text
    axes[2].axis('off')
    summary_text = (
        f'SUMMARY STATISTICS\n'
        f'{'─'*30}\n\n'
        f'Total Images      : {total_img}\n'
        f'Tiger Images      : {len(tiger_images)}\n'
        f'No Tiger Images   : {len(no_tiger_images)}\n'
        f'Unusable Images   : {len(unusable_images)}\n\n'
        f'Total Detections  : {total_detections}\n\n'
        f'Detection Rate    : {len(tiger_images)/total_img*100:.1f}%\n'
        f'Usability Rate    : {(total_img-len(unusable_images))/total_img*100:.1f}%\n'
    )
    axes[2].text(0.05, 0.95, summary_text,
                 transform=axes[2].transAxes,
                 fontsize=12, verticalalignment='top',
                 fontfamily='monospace',
                 bbox=dict(boxstyle='round', facecolor='lightyellow',
                           alpha=0.8))
    axes[2].set_title('Quick Stats')

    plt.tight_layout()
    plt.show()

    print('\n✅ COMPLETE ANALYSIS FINISHED!')
    print(f'   Report saved to Google Drive: {REPORT_PATH}')

"""---
## SECTION 6 — UTILITIES
### Cell 6.1 — Test on a Specific Image by Filename
"""

# ============================================================
# CELL 6.1 — TEST ON ANY SPECIFIC IMAGE
# Change the filename below to test any image
# ============================================================

# ← Change this to your image filename
SPECIFIC_IMAGE = '000013.jpg'

image_path = os.path.join(TEST_IMAGES_PATH, SPECIFIC_IMAGE)

if os.path.exists(image_path):
    result = analyze_image(
        image_path,
        conf_threshold = 0.35,
        iou_threshold  = 0.50,
        show_result    = True
    )
else:
    print(f'❌ Image not found: {image_path}')
    print(f'   Available images in test_images folder:')
    for f in os.listdir(TEST_IMAGES_PATH):
        print(f'   → {f}')

"""### Cell 6.2 — Reload Models (If Colab Session Restarted)"""

# ============================================================
# CELL 6.2 — RELOAD MODELS AFTER SESSION RESTART
# Run this ONLY if your Colab session disconnected
# and you need to reload without retraining
# ============================================================

# 1. Re-mount drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Re-run Cell 1.2 (install libraries)
import subprocess
subprocess.run(['pip', 'install', 'ultralytics', '-q'])

# 3. Reload all imports
from ultralytics import YOLO
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
import os, warnings
warnings.filterwarnings('ignore')

# 4. Re-run Cell 1.3 (configure paths)
PROJECT_ROOT      = '/content/drive/MyDrive/Tiger_Project'
DATASET_PATH      = f'{PROJECT_ROOT}/dataset'
TIGER_TYPES_PATH  = f'{PROJECT_ROOT}/tiger_types'
MODELS_PATH       = f'{PROJECT_ROOT}/models'
TEST_IMAGES_PATH  = f'{PROJECT_ROOT}/test_images'
YOLO_MODEL_PATH   = f'{MODELS_PATH}/tiger_detector/weights/best.pt'
EFFNET_MODEL_PATH = f'{MODELS_PATH}/tiger_classifier.keras'

TIGER_TYPES = ['black_tiger', 'golden_tiger', 'orange_tiger',
               'snow_white_tiger', 'white_tiger']

TYPE_DISPLAY_NAMES = {
    'black_tiger'      : 'Black Tiger',
    'golden_tiger'     : 'Golden Tiger',
    'orange_tiger'     : 'Orange Tiger',
    'snow_white_tiger' : 'Snow White Tiger',
    'white_tiger'      : 'White Tiger'
}

BOX_COLORS = {
    'black_tiger'      : (50,  50,  50),
    'golden_tiger'     : (255, 215, 0),
    'orange_tiger'     : (255, 140, 0),
    'snow_white_tiger' : (200, 200, 255),
    'white_tiger'      : (255, 255, 255)
}

# 5. Reload trained models
print('Loading saved models...')

if os.path.exists(YOLO_MODEL_PATH):
    yolo_model = YOLO(YOLO_MODEL_PATH)
    print(f'✅ YOLO model loaded from {YOLO_MODEL_PATH}')
else:
    print(f'❌ YOLO model not found at {YOLO_MODEL_PATH}')
    print('   Please run Section 3 (Cell 3.2) to train it first.')

if os.path.exists(EFFNET_MODEL_PATH):
    classifier_model = tf.keras.models.load_model(EFFNET_MODEL_PATH)
    print(f'✅ Classifier model loaded from {EFFNET_MODEL_PATH}')
else:
    print(f'❌ Classifier model not found at {EFFNET_MODEL_PATH}')
    print('   Please run Section 4 (Cell 4.3) to train it first.')

# 6. Rebuild class mapping
from tensorflow.keras.preprocessing.image import ImageDataGenerator
temp_gen = ImageDataGenerator(rescale=1./255)
temp_data = temp_gen.flow_from_directory(
    TIGER_TYPES_PATH,
    target_size = (300, 300),
    batch_size  = 1,
    class_mode  = 'categorical',
    shuffle     = False
)
CLASS_INDICES = temp_data.class_indices
CLASS_NAMES   = {v: k for k, v in CLASS_INDICES.items()}
NUM_CLASSES   = len(CLASS_INDICES)

print(f'\n✅ Session restored successfully!')
print(f'   Class mapping: {CLASS_INDICES}')
print()
print('You can now run Cell 5.2 or Cell 5.4 directly.')

"""---
## QUICK REFERENCE

| Issue | Solution |
|---|---|
| Seeing 5 boxes on 1 tiger | Run Cell 5.3, increase `conf_threshold` to 0.5–0.6 |
| Missing real tigers | Decrease `conf_threshold` to 0.2–0.25 |
| Session disconnected | Run Cell 6.2 to reload models |
| Low classifier accuracy | Collect more images per tiger type |
| Dark night images failing | Already handled automatically in pipeline |
| Want to test new image | Upload to `test_images/`, run Cell 5.2 |
| Want full report | Upload all images to `test_images/`, run Cell 5.4 |

---
*Tiger AI System — Built for Forest Department Wildlife Monitoring*  
*Models: YOLOv8s (Detection) + EfficientNetB3 (Classification)*
"""